version: '3'
services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050"
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase  # Refer to MongoDB service by name
    # No need for `networks` or `depends_on`

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"
    environment:
      REACT_APP_API_URL: http://backend:5050  # Refer to backend service by name
    # No need for `networks`

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db  # Use host volume for persistence
    # No need for `networks`
